springdoc:
  swagger-ui:
    path: /api
    enabled: true
  cache:
    disabled: true
  use-fqn: true

spring:
  config:
    activate:
      on-profile: supabase-dev

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${SUPABASE_DB_HOST}:${SUPABASE_DB_PORT}/${SUPABASE_DB_NAME}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

xumm:
  api-key: ${XUMM_API_KEY}
  api-secret: ${XUMM_API_SECRET}
  webhook-url: ${XUMM_WEBHOOK_URL:}
  return-url: ${XUMM_RETURN_URL:}
  expiration-minutes: 10
