server:
  port: 8080

logging:
  level:
    org.springdoc: off
    org.hibernate.SQL: DEBUG                               # SQL 실행 쿼리 로그를 출력
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE   # 바인딩된 파라미터 값을 출력
    org.hibernate.orm.jdbc.bind: TRACE                     # Alternative for newer Hibernate versions

spring:
  application:
    name: xrpl

  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true
        page-parameter: page
        size-parameter: size

xrpl:
  network-id: testnet
  rpc-url: https://s.devnet.rippletest.net:51234
  central-wallet-address: ${XRPL_CENTRAL_WALLET_ADDRESS:rc1MRgyCzWnBaZqh8idSUmC1YhYgSxDk9}
  central-wallet-secret: ${XRPL_CENTRAL_WALLET_SECRET:sEd7sZVeH7Ucw78ZEMwWVdZ726kUvYC}
  polling-interval-ms: 30000
  nft-issuer-address: ${XRPL_NFT_ISSUER_ADDRESS:rKWHLdanG4awzUwQPKdVJarapERRZhVeyV}
  nft-issuer-secret: ${XRPL_NFT_ISSUER_SECRET:sEdVSA2F82BbpuizqWRAAqrmRRxDrVm}
  nft-uri-prefix: https://example.com/metadata/
