springdoc:
  swagger-ui:
    path: /api
    enabled: true
  cache:
    disabled: true
  use-fqn: true

spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 785842157414-ur8enblqoqsnnp1rrs2f8bqqea27bhhh.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - profile
              - email

jwt:
  secret-key: "Zp7s5v8y/B?E(H+MbQeThWmZq4t6w9z$C&F)J@NcRfUjXn2r5u8x!A%D*G-KaPdS"
  access-token-expire-time: 3600000 # 1시간 (밀리초 단위)
  refresh-token-expire-time: 604800000 # 7일 (밀리초 단위)
